# Change these first
owner: poppin-fresh # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Elevated Website
    url: https://elevatedservers.com/
  - name: Elevated Game Panel
    url: https://panel.elevatedservers.com/
  - name: Hacker News
    url: https://us1.elevatedservers.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: uptime.elevatedservers.com
  baseUrl: /uptime
  logoUrl: https://elevatedservers.com/img/justcloud.png
  name: Elevated Servers Status HUB
  introTitle: ""
  introMessage: 
  navbar:
    - title: Elevated Servers Monitor
      href: https://elevatedservers.com/
    - title: Game Panel
      href: https://panel.elevatedservers.com/
i18n:
  footer: Status Monitor for [Elevated Servers](https://elevatedservers.com)
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
